from typing import Any, Dict, List, Protocol

class IEmbedder(Protocol):
    def embed(self, texts: List[str]) -> List[List[float]]: ...

class IVectorStore(Protocol):
    def ensure(self) -> None: ...
    def upsert(self, records: List[Dict[str, Any]]) -> None: ...
    def search(self, q_vec: List[float], k: int = 8) -> List[Dict[str, Any]]: ...