version = 0.1

[default.deploy.parameters]
stack_name = "slack-rag-v2"
resolve_s3 = true
s3_prefix = "slack-rag"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ArtifactsBucket=\"slack-rag-artifacts-73918652\" ModelName=\"sentence-transformers/all-MiniLM-L6-v2\" IndexPrefix=\"rag/index\" FaissKey=\"rag/index/faiss.index\" MetaKey=\"rag/index/meta.json\" SlackSigningSecretArn=\"arn:aws:secretsmanager:us-east-1:471112701253:secret:slack/signing-secret-n7WDeM\" SlackBotTokenArn=\"arn:aws:secretsmanager:us-east-1:471112701253:secret:rag/slack/bot_token-tZy5lT\" RagApiUrl=\"https://z4n0qub7cc.execute-api.us-east-1.amazonaws.com/Prod/chat\""
image_repositories = []
disable_rollback = true
