AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RAG FastAPI + Slack (no layers)

Parameters:
  ArtifactsBucket:               { Type: String }
  ModelName:                     { Type: String, Default: sentence-transformers/all-MiniLM-L6-v2 }
  IndexPrefix:                   { Type: String, Default: rag/index }
  FaissKey:                      { Type: String, Default: rag/index/faiss.index }
  MetaKey:                       { Type: String, Default: rag/index/meta.json }
  SlackSigningSecretArn:         { Type: String }
  SlackBotTokenArn:              { Type: String }
  RagApiUrl:                     { Type: String }

Globals:
  Function:
    Runtime: python3.11
    Architectures: [arm64]  # Use ARM architecture for better performance/cost
    Timeout: 30
    MemorySize: 2048
    Environment:
      Variables:
        APP_ENV: prod
        ARTIFACTS_BUCKET: !Ref ArtifactsBucket
        MODEL_NAME: !Ref ModelName
        INDEX_PREFIX: !Ref IndexPrefix
        FAISS_KEY: !Ref FaissKey
        META_KEY: !Ref MetaKey
        EMBEDDER_PROVIDER: bedrock
        # AWS_REGION: !Ref AWS::Region
        BEDROCK_REGION: !Ref AWS::Region

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowMethods: ["GET", "POST", "OPTIONS"]
        AllowHeaders: ["*"]
        AllowOrigins: ["*"]

  RAGApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src            # <- your repo's src/
      Handler: rag.api.app.handler
      Policies:
        - S3ReadPolicy: { BucketName: !Ref ArtifactsBucket }
        - AWSSecretsManagerGetSecretValuePolicy: { SecretArn: !Ref SlackSigningSecretArn }
        - AWSSecretsManagerGetSecretValuePolicy: { SecretArn: !Ref SlackBotTokenArn }
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
      Events:
        AnyRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

  SlackEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../handlers       # <- your repo's handlers/
      Handler: slack_events.handler
      # CodeUri: ../src          # ← same code root; it will reuse the same deps bundle
      # Handler: handlers/slack_events.handler
      Runtime: python3.11
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          RagApiUrl: !Ref RagApiUrl
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy: { SecretArn: !Ref SlackSigningSecretArn }
        - AWSSecretsManagerGetSecretValuePolicy: { SecretArn: !Ref SlackBotTokenArn }
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
      Events:
        SlackEventsRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /slack/events
            Method: POST

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  SlackEventsUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack/events"
  ChatApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat"