name: CI
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches-ignore: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      # Force pure-local mode so CI never touches AWS
      APP_ENV: "local"
      USE_S3_INDEX: "false"
      EMBED_PROVIDER: "local"
      MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
      EMBED_DIM: "384"
      LLM_PROVIDER: "none"
      # retrieval knobs (safe defaults)
      RETRIEVE_K: "24"
      CONTEXT_K: "8"
      FALLBACK_MIN_SCORE: "0.32"
      ANSWER_FALLBACK: "allow"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            src/requirements-dev.txt
            src/requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements-dev.txt ]; then pip install -r src/requirements-dev.txt; fi
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Unit & smoke tests
        run: |
          pytest -q

