name: CI
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches-ignore: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
      # Force pure-local mode so CI never touches AWS
      APP_ENV: "local"
      USE_S3_INDEX: "false"
      EMBED_PROVIDER: "local"
      MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
      EMBED_DIM: "384"
      LLM_PROVIDER: "none"
      # retrieval knobs (safe defaults)
      RETRIEVE_K: "24"
      CONTEXT_K: "8"
      FALLBACK_MIN_SCORE: "0.32"
      ANSWER_FALLBACK: "allow"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('src/requirements-dev.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: ${{ env.HF_HOME }}
          key: hf-${{ runner.os }}-${{ env.MODEL_NAME }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements-dev.txt

      - name: Lint import / quick sanity
        run: |
          python - <<'PY'
          import importlib; import sys
          sys.path.append("src")
          importlib.import_module("rag.api.app")
          print("app import OK")
          PY

      - name: Run tests
        run: |
          pytest -q
